{
 "title": "Cross build statistics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "select distinct project_id from build_trends"
   },
   {
    "name": "taskName",
    "query": "select distinct task_path from task_trends t join build_trends b on (b.build_id = t.build_id) where project_id like '${project:raw}'"
   },
   {
    "name": "status",
    "query": "select distinct status from task_trends t join build_trends b on (b.build_id = t.build_id) where project_id like '${project:raw}' and task_path like '${taskName:raw}'"
   },
   {
    "name": "taskNameCacheable",
    "query": "select distinct task_path from task_trends t join build_trends b on (b.build_id = t.build_id) where status = 'executed_cacheable' and project_id = '${project:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Miss Ratio (${taskNameCacheable:raw})",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    avg(case when status = 'executed_cacheable' then 1\n             else 0\n        end) as cache_miss\nFROM task_trends\nwhere task_path like '${taskNameCacheable:raw}'\n"
    }
   ]
  },
  {
   "title": "Tasks with >70% Cache Misses",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n        avg(case when status = 'executed_cacheable' then 1\n          else 0\n        end) as cache_miss,\n        task_path\nFROM task_trends t join build_trends b on (b.build_id = t.build_id)\nwhere project_id like '${project:raw}'\nand $__timeFilter(b.build_start)\nand 'CI' = any(tags)\ngroup by task_path\nhaving avg(case when status = 'executed_cacheable' then 1\n                else 0\n    end) * 100 > 30\n    and count(*) > 5\n    order by 1 desc"
    }
   ]
  },
  {
   "title": "Task duration (${taskName:raw} with ${status:raw})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select task_duration_ms, build_start as \"time\"\nfrom task_trends t join build_trends b on (b.build_id = t.build_id)\nwhere status like '${status:raw}'\nand task_path like '${taskName:raw}'"
    }
   ]
  },
  {
   "title": "Cache miss hall of shame",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(case when status = 'executed_cacheable' then 1\n       else 0\n  end) as cache_miss,\n  task_path\nFROM build_trends build, task_trends tasks\nwhere $__timeFilter(build.build_start)\nand build.build_id = tasks.build_id\nand project_id = ${project}\nand 'CI' = any(tags)\ngroup by tasks.task_path\nhaving count(*) > 5\nand avg(case when status = 'executed_cacheable' then 1\n       else 0\n  end) > 0.1\norder by 1 desc\n"
    }
   ]
  }
 ]
}