name: gradle-bot-CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Gradle Check
      uses: gradle/gradle-build-action@v2
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_GRADLE_ORG_ACCESS_TOKEN }}
      with:
        arguments: check
